spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://root:123@localhost:27019/notification_db?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    topic:
      order-created: order-created
      order-confirmed: order-confirmed
      order-fail: order-fail

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: ${MAIL_DEFAULT_ENCODING}
    protocol: ${MAIL_PROTOCOL}

  config:
    import: optional:file:../.env


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true