spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://root:123@localhost:27018/order_db?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
    topic:
      order-created: order-created
      order-confirmed: order-confirmed
      order-fail: order-fail

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true


