spring:
  application:
    name: product-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product_db
      authentication-database: admin
      username: root
      password: 123

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true